chore: clear generate logic: 1.ca 2.domain

diff --git a/core/generate b/core/generate
--- a/core/generate
+++ b/core/generate
@@ -6,29 +6,72 @@ local_https::command_exists() {
   type "$1" &>/dev/null
 }
 
-local_https::generate() {
-  set -e
+local_https::create_ca_and_register_certificate() {
+  if [ ! -f "$PLUGIN_LOCAL_HTTPS_ROOT_CA_PRIVATE_KEY" ]; then
+    log::info "generate ca private key ..."
+    # need password
+    # openssl genrsa -des3 -out "$PLUGIN_LOCAL_HTTPS_ROOT_CA_PRIVATE_KEY" 2048 >> /dev/null 2>&1
+    # no password
+    sudo openssl genrsa -out "$PLUGIN_LOCAL_HTTPS_ROOT_CA_PRIVATE_KEY" 2048 >>/dev/null 2>&1
+    sudo chmod 600 $PLUGIN_LOCAL_HTTPS_ROOT_CA_PRIVATE_KEY
+
+    rm -rf $PLUGIN_LOCAL_HTTPS_ROOT_CA_SELF_CERTIFICATE
+  fi
+
+  if [ ! -f "$PLUGIN_LOCAL_HTTPS_ROOT_CA_SELF_CERTIFICATE" ]; then
+    # 注意：证书颁发机构 CA 有效时间不受苹果系统域名 825 天限制，也就是可以是 3650 天（10年），与下文签发具体域名证书对比
+    log::info "generate ca certtificate ..."
+    sudo openssl req -x509 \
+      -config $PLUGIN_LOCAL_HTTPS_ROOT_CA_REQUEST_CONFIG \
+      -new -nodes \
+      -key "$PLUGIN_LOCAL_HTTPS_ROOT_CA_PRIVATE_KEY" \
+      -sha256 \
+      -days 3650 \
+      -out "$PLUGIN_LOCAL_HTTPS_ROOT_CA_SELF_CERTIFICATE" >>/dev/null 2>&1
+    # -days 825 \
+    sudo chmod 600 $PLUGIN_LOCAL_HTTPS_ROOT_CA_SELF_CERTIFICATE
+  fi
+
+  # MacOS
+  if local_https::command_exists security; then
+    log::info "write self signed ca to system ..."
+
+    if [ "$(sudo security find-certificate -c "${PLUGIN_LOCAL_HTTPS_ROOT_CA_COMMON_NAME}" -a -Z)" = "" ]; then
+      # Delete trusted certs by their common name via https://unix.stackexchange.com/a/227014
+      sudo security find-certificate -c "${PLUGIN_LOCAL_HTTPS_ROOT_CA_COMMON_NAME}" -a -Z | sudo awk '/SHA-1/{system("security delete-certificate -Z "$NF)}'
+
+      # Trust the Root Certificate cert
+      sudo security add-trusted-cert \
+        -d \
+        -r trustRoot \
+        -k /Library/Keychains/System.keychain \
+        "$PLUGIN_LOCAL_HTTPS_ROOT_CA_SELF_CERTIFICATE"
+    fi
+  elif local_https::command_exists dpkg-reconfigure; then
+    local YesNo=(Yes No)
+    inquirer::select "Please check $($PLUGIN_LOCAL_HTTPS_ROOT_CA_SELF_CERTIFICATE) in next step, are you ready ?" YesNo ok
+    if [ "$ok" != "Yes" ]; then
+      log::error "You have cancel it"
+      exit 1
+    fi
+
+    sudo copy $PLUGIN_LOCAL_HTTPS_ROOT_CA_SELF_CERTIFICATE /usr/share/ca-certificates/$PLUGIN_LOCAL_HTTPS_ROOT_CA_SELF_CERTIFICATE
+    sudo dpkg-reconfigure ca-certificates
+  fi
+}
+
+local_https::generate_domain_certificate() {
+  # set -e
   local domain=$1
   local is_wildcard=$2 # true | false
 
-  local config_dir=${PLUGIN_DIR}/config
-  local ca_common_name="LOCAL HTTPS/TLS CA"
-  local ca_data_dir=$PLUGIN_LOCAL_HTTPS_CERTS/ca
-  local ca_key=$ca_data_dir/root_ca.key
-  local ca_crt=$ca_data_dir/root_ca.crt
-  local ca_request_config=$config_dir/conf/ca/certificate-authority-request.conf
-
-  local domain_data_dir=$PLUGIN_LOCAL_HTTPS_CERTS/domain/$domain
+  local domain_data_dir=$PLUGIN_LOCAL_HTTPS_DOMAIN_DATA_DIR/$domain
   local domain_request_config=$domain_data_dir/domain-request.conf
   local domain_extfile_config=$domain_data_dir/domain-extfile.conf
   local domain_key=$domain_data_dir/server.key
   local domain_csr=$domain_data_dir/server.csr
   local domain_crt=$domain_data_dir/server.crt
   # local data_tmp=$domain_data_dir/tmp
-
-  if [ ! -d "$ca_data_dir" ]; then
-    mkdir -p $ca_data_dir
-  fi
 
   if [ ! -d "$domain_data_dir" ]; then
     mkdir -p $domain_data_dir
@@ -43,70 +86,18 @@ local_https::generate() {
 
   cd $domain_data_dir
 
-  if [ ! -f "$ca_key" ]; then
-    log::info "generate ca private key ..."
-    # need password
-    # openssl genrsa -des3 -out "$ca_key" 2048 >> /dev/null 2>&1
-    # no password
-    sudo openssl genrsa -out "$ca_key" 2048 >>/dev/null 2>&1
-    sudo chmod 600 $ca_key
-
-    rm -rf $ca_crt
-  fi
-
-  if [ ! -f "$ca_crt" ]; then
-    # 注意：证书颁发机构 CA 有效时间不受苹果系统域名 825 天限制，也就是可以是 3650 天（10年），与下文签发具体域名证书对比
-    log::info "generate ca certtificate ..."
-    sudo openssl req -x509 \
-      -config $ca_request_config \
-      -new -nodes \
-      -key "$ca_key" \
-      -sha256 \
-      -days 3650 \
-      -out "$ca_crt" >>/dev/null 2>&1
-    # -days 825 \
-    sudo chmod 600 $ca_crt
-  fi
-
-  # MacOS
-  if local_https::command_exists security; then
-    log::info "write self signed ca to system ..."
-
-    if [ "$(sudo security find-certificate -c "${ca_common_name}" -a -Z)" = "" ]; then
-      # Delete trusted certs by their common name via https://unix.stackexchange.com/a/227014
-      sudo security find-certificate -c "${ca_common_name}" -a -Z | sudo awk '/SHA-1/{system("security delete-certificate -Z "$NF)}'
-
-      # Trust the Root Certificate cert
-      sudo security add-trusted-cert \
-        -d \
-        -r trustRoot \
-        -k /Library/Keychains/System.keychain \
-        "$ca_crt"
-    fi
-  elif local_https::command_exists dpkg-reconfigure; then
-    local YesNo=(Yes No)
-    inquirer::select "Please check $($ca_crt) in next step, are you ready ?" YesNo ok
-    if [ "$ok" != "Yes" ]; then
-      log::error "You have cancel it"
-      exit 1
-    fi
-
-    sudo copy $ca_crt /usr/share/ca-certificates/$ca_crt
-    sudo dpkg-reconfigure ca-certificates
-  fi
-
   log::info "generate https(ssl) for domain (${domain}) ..."
 
   if [ "$is_wildcard" = "true" ]; then
     log::info "generate wildcard domain (*.$domain) request config ..."
-    sed "s/local.dev/*."$domain"/" $config_dir/conf/domain/domain-request.conf >$domain_request_config
+    sed "s/local.dev/*."$domain"/" $PLUGIN_LOCAL_HTTPS_DOMAIN_REQUEST_CONFIG_TEMPLATE >$domain_request_config
     log::info "generate domain extfile config ..."
-    sed "s/local.dev/"$domain"/" $config_dir/conf/domain/domain-extfile.conf >$domain_extfile_config
+    sed "s/local.dev/"$domain"/" $PLUGIN_LOCAL_HTTPS_DOMAIN_EXTFILE_CONFIG_TEMPLATE >$domain_extfile_config
   else
     log::info "generate domain ($domain) request config ..."
-    sed "s/local.dev/"$domain"/" $config_dir/conf/domain/domain-request.conf >$domain_request_config
+    sed "s/local.dev/"$domain"/" $PLUGIN_LOCAL_HTTPS_DOMAIN_REQUEST_CONFIG_TEMPLATE >$domain_request_config
     log::info "generate domain extfile config ..."
-    sed "s/local.dev/"$domain"/" $config_dir/conf/domain/domain-extfile.conf >$domain_extfile_config
+    sed "s/local.dev/"$domain"/" $PLUGIN_LOCAL_HTTPS_DOMAIN_EXTFILE_CONFIG_TEMPLATE >$domain_extfile_config
   fi
 
   if [ ! -f "$domain_key" ]; then
@@ -131,8 +122,8 @@ local_https::generate() {
   # including custom roots. See https://support.apple.com/en-us/HT210176.
   sudo openssl x509 \
     -req \
-    -CA "$ca_crt" \
-    -CAkey "$ca_key" \
+    -CA "$PLUGIN_LOCAL_HTTPS_ROOT_CA_SELF_CERTIFICATE" \
+    -CAkey "$PLUGIN_LOCAL_HTTPS_ROOT_CA_PRIVATE_KEY" \
     -CAcreateserial \
     -days 825 \
     -sha256 \
@@ -158,8 +149,26 @@ local_https::generate() {
   log::success "#####################################"
   echo ""
 
-  set +e
+  # set +e
+}
+
+local_https::generate() {
+  local_https::create_ca_and_register_certificate
+  if [ "$?" != "0" ]; then
+    log::error "failed to create ca and register certificate ."
+    return 1
+  fi
+  
+  local_https::generate_domain_certificate "$@"
+  if [ "$?" != "0" ]; then
+    log::error "failed to generate domain certificate."
+    return 1
+  fi
 }
 
 export -f local_https::command_exists
+
+export -f local_https::create_ca_and_register_certificate
+export -f local_https::generate_domain_certificate
+
 export -f local_https::generate
